-- =====================================================================
--  UCAM STEREO — PARTE 1: ESTRUCTURA (CREATE TABLE)        v5
--  PostgreSQL 15+ / Supabase — Soluciones Informáticas para la Empresa
--
--  Modelo alineado con el frontend (PaginaVenta: data/products.js,
--  lib/pricing.js, lib/orders.js, lib/events.js, context/*, pages/*).
--  Borra todas las tablas y datos anteriores y crea las 14 tablas,
--  índices, trigger, función, vista y RLS.
--  Ejecutar ANTES de 02_datos.sql.
--
--  Cambios respecto a v3 (todos para ser fieles al frontend):
--   · Variantes: cada producto tiene UNA variante base (finish/color de
--     products.js) + las de `variants`. Stock solo en variante_producto.
--     Desaparecen color y acabado (el frontend usa texto libre) y
--     precio_adicional (todas las variantes cuestan lo mismo).
--   · cliente: + rol ('cliente'|'admin'); se elimina el flag de primer
--     pedido: el descuento del 10 % dura un mes natural desde el alta
--     (pricing.js) -> función descuento_bienvenida_hasta().
--   · pedido: nº `UC-AAAA-NNNNN`, estados y reglas de envío/IVA del
--     frontend, email de contacto, sin notas/piso (ya no existen en el
--     formulario) ni código de descuento (el descuento es automático).
--   · pago: método `paypal_simulado`, resultado approved/declined.
--   · incidencia: datos del formulario de Soporte (pedido opcional).
--   · evento: 7 tipos (+ order.status_changed) y sesión del navegador.
--   · producto: sin gama ni galería (no existen en el frontend);
--     compatibilidad es texto; categoria.cta sustituye a titular.
--
--  Cambios de v5 (revisión de código):
--   · producto.especificaciones pasa de JSONB a JSON: JSONB reordena las
--     claves y la web pinta la ficha técnica en el orden de products.js.
--   · pedido.numero_pedido se genera en la base de datos (secuencia): el
--     contador del frontend es por pestaña y produciría números repetidos.
--   · Protección contra duplicados: un pago aprobado por pedido, un pedido
--     por carrito y un carrito activo por cliente.
--   · CHECK del descuento: solo 0 o el 10 % del subtotal (DISCOUNT_RATE).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 0. LIMPIEZA: elimina tablas y datos anteriores (incluye las de v3)
-- ---------------------------------------------------------------------
DROP VIEW     IF EXISTS v_catalogo;
DROP TABLE IF EXISTS evento            CASCADE;
DROP TABLE IF EXISTS incidencia        CASCADE;
DROP TABLE IF EXISTS pago              CASCADE;
DROP TABLE IF EXISTS linea_pedido      CASCADE;
DROP TABLE IF EXISTS pedido            CASCADE;
DROP TABLE IF EXISTS linea_carrito     CASCADE;
DROP TABLE IF EXISTS carrito           CASCADE;
DROP TABLE IF EXISTS sesion            CASCADE;
DROP TABLE IF EXISTS producto_conexion CASCADE;
DROP TABLE IF EXISTS variante_producto CASCADE;
DROP TABLE IF EXISTS acabado           CASCADE;   -- v3
DROP TABLE IF EXISTS color             CASCADE;   -- v3
DROP TABLE IF EXISTS conexion          CASCADE;
DROP TABLE IF EXISTS producto          CASCADE;
DROP TABLE IF EXISTS categoria         CASCADE;
DROP TABLE IF EXISTS cliente           CASCADE;
DROP FUNCTION IF EXISTS set_fecha_actualizacion() CASCADE;
DROP FUNCTION IF EXISTS descuento_bienvenida_hasta(timestamptz) CASCADE;
DROP SEQUENCE IF EXISTS seq_numero_pedido;

-- pgcrypto: hash de contraseñas con sal (bcrypt). En Supabase ya existe.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------
-- 1. ESQUEMA
-- ---------------------------------------------------------------------

-- CATEGORÍA (CATEGORIES de products.js) ---------------------------------
CREATE TABLE categoria (
    id_categoria   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(40)  NOT NULL UNIQUE,      -- 'vinilos', 'tocadiscos'…
    nombre         VARCHAR(80)  NOT NULL UNIQUE,
    descripcion    TEXT         NOT NULL,
    cta            VARCHAR(60)  NOT NULL,             -- texto del botón: 'Ver tocadiscos'
    imagen         TEXT         NOT NULL,
    orden          SMALLINT     NOT NULL DEFAULT 0
);

-- PRODUCTO (PRODUCTS de products.js) ------------------------------------
-- El stock NO está aquí: vive en variante_producto (ver v_catalogo).
CREATE TABLE producto (
    id_producto      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria     INT           NOT NULL REFERENCES categoria(id_categoria) ON DELETE RESTRICT,
    codigo           VARCHAR(10)   NOT NULL UNIQUE CHECK (codigo ~ '^p[0-9]{3}$'),  -- id del frontend: 'p001'
    slug             VARCHAR(80)   NOT NULL UNIQUE,
    nombre           VARCHAR(150)  NOT NULL,          -- name
    marca            VARCHAR(80)   NOT NULL,          -- brand
    descripcion      TEXT          NOT NULL,
    tipo_variante    VARCHAR(10)   NOT NULL CHECK (tipo_variante IN ('Acabado','Color')),
                                                      -- 'Acabado' si el producto define finish, 'Color' si define color
    precio           NUMERIC(10,2) NOT NULL CHECK (precio >= 0),   -- IVA incluido; igual para todas las variantes
    imagen           TEXT          NOT NULL,
    caracteristicas  JSONB         NOT NULL DEFAULT '[]'::jsonb,   -- features
    especificaciones JSON          NOT NULL DEFAULT '{}'::json,    -- specs (JSON, no JSONB: conserva el orden de las filas; no admite DISTINCT/UNION/=, usar ::jsonb si hace falta)
    compatibilidad   TEXT          NOT NULL,                       -- compatibility (texto)
    valoracion       NUMERIC(2,1)  NOT NULL CHECK (valoracion BETWEEN 0 AND 5),  -- rating
    num_resenas      INT           NOT NULL DEFAULT 0 CHECK (num_resenas >= 0),  -- reviews
    etiqueta         VARCHAR(40),                                  -- badge (opcional)
    destacado        BOOLEAN       NOT NULL DEFAULT FALSE,         -- featured
    activo           BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion   TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_producto_categoria ON producto(id_categoria);

-- CONEXIÓN + PRODUCTO_CONEXIÓN (N:M) -----------------------------------
CREATE TABLE conexion (
    id_conexion  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE producto_conexion (
    id_producto  INT NOT NULL REFERENCES producto(id_producto) ON DELETE CASCADE,
    id_conexion  INT NOT NULL REFERENCES conexion(id_conexion) ON DELETE CASCADE,
    PRIMARY KEY (id_producto, id_conexion)
);
CREATE INDEX idx_producto_conexion_conexion ON producto_conexion(id_conexion);

-- VARIANTE DE PRODUCTO --------------------------------------------------
-- Replica el modelo del frontend: la opción "original" del producto
-- (finish/color, id de variante null, stock = product.stock) y cada
-- elemento de `variants`. La clave del carrito es 'p001' (base) o
-- 'p001:aluminio-cepillado'. Es el ÚNICO sitio donde se guarda el stock.
CREATE TABLE variante_producto (
    id_variante     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto     INT          NOT NULL REFERENCES producto(id_producto) ON DELETE CASCADE,
    codigo          VARCHAR(40),                              -- id de la variante en el frontend; NULL = base
    es_base         BOOLEAN      NOT NULL DEFAULT FALSE,
    valor           VARCHAR(60)  NOT NULL,                    -- 'Negro mate', 'Aluminio cepillado'…
    sku             VARCHAR(40)  NOT NULL UNIQUE,
    stock           INT          NOT NULL DEFAULT 0 CHECK (stock >= 0),
    imagen          TEXT,                                     -- el frontend usa variant.image ?? product.image
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_variante_base CHECK (es_base = (codigo IS NULL)),
    UNIQUE (id_producto, codigo),
    UNIQUE (id_producto, valor),
    UNIQUE (id_variante, id_producto)        -- necesaria para la FK compuesta de las líneas
);
CREATE UNIQUE INDEX uq_variante_base ON variante_producto(id_producto) WHERE es_base;   -- una base por producto

-- CLIENTE --------------------------------------------------------------
-- Registrado (tiene contraseña) o invitado (Checkout sin sesión: guest).
-- fecha_creacion = joinedAt del frontend (inicio del mes de descuento).
CREATE TABLE cliente (
    id_cliente      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(120) NOT NULL,
    apellidos       VARCHAR(160),                              -- el registro solo pide "name"; el checkout sí separa apellidos
    email           VARCHAR(254) NOT NULL,
    telefono        VARCHAR(30),
    password_hash   TEXT,                                      -- NULL = invitado
    registrado      BOOLEAN      NOT NULL DEFAULT FALSE,
    rol             VARCHAR(10)  NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente','admin')),
    newsletter      BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_registrado_password CHECK (registrado = FALSE OR password_hash IS NOT NULL),
    CONSTRAINT chk_admin_registrado    CHECK (rol = 'cliente' OR registrado)
);
CREATE UNIQUE INDEX uq_cliente_email ON cliente (lower(email));

-- Fin del descuento de bienvenida: un mes natural desde el alta, ajustado
-- al último día del mes de destino (welcomeEndsAt de pricing.js; calculado en UTC).
-- Aplica a rol = 'cliente' mientras  alta <= ahora < descuento_bienvenida_hasta(alta).
CREATE FUNCTION descuento_bienvenida_hasta(alta timestamptz) RETURNS timestamptz
LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = ''
AS $$ SELECT ((alta AT TIME ZONE 'UTC') + interval '1 month') AT TIME ZONE 'UTC' $$;

-- SESIÓN (PDF 5.6: sesiones con caducidad y token guardado como hash) ---
-- El frontend aún usa sessionStorage; la tabla queda lista para el backend.
CREATE TABLE sesion (
    id_sesion         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente        INT         NOT NULL REFERENCES cliente(id_cliente) ON DELETE CASCADE,
    token_hash        TEXT        NOT NULL UNIQUE,
    fecha_expiracion  TIMESTAMPTZ NOT NULL,
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sesion_cliente ON sesion(id_cliente);

-- CARRITO + LÍNEA DE CARRITO -------------------------------------------
CREATE TABLE carrito (
    id_carrito           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente           INT         REFERENCES cliente(id_cliente) ON DELETE SET NULL,
    estado               VARCHAR(12) NOT NULL DEFAULT 'ACTIVO'
                         CHECK (estado IN ('ACTIVO','CONVERTIDO','ABANDONADO')),
    fecha_creacion       TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_actualizacion  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_carrito_cliente ON carrito(id_cliente);
CREATE UNIQUE INDEX uq_carrito_activo ON carrito(id_cliente) WHERE estado = 'ACTIVO';   -- un carrito activo por cliente

CREATE TABLE linea_carrito (
    id_lineacarrito  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito       INT NOT NULL REFERENCES carrito(id_carrito) ON DELETE CASCADE,
    id_producto      INT NOT NULL REFERENCES producto(id_producto) ON DELETE RESTRICT,
    id_variante      INT NOT NULL,                 -- siempre hay variante (la base también lo es): cartKey del frontend
    cantidad         INT NOT NULL CHECK (cantidad > 0),
    -- La variante tiene que pertenecer al mismo producto de la línea
    FOREIGN KEY (id_variante, id_producto)
        REFERENCES variante_producto(id_variante, id_producto) ON DELETE RESTRICT,
    UNIQUE (id_carrito, id_variante)
);
CREATE INDEX idx_linea_carrito_variante ON linea_carrito(id_variante, id_producto);
CREATE INDEX idx_linea_carrito_producto ON linea_carrito(id_producto);

-- PEDIDO + LÍNEA DE PEDIDO ---------------------------------------------
-- numero_pedido = order.id de orders.js (`UC-AAAA-NNNNN`; las pantallas
-- de confirmación y seguimiento lo muestran con prefijo UCS-).
-- Lo genera la base de datos (como nextOrderId(): contador que empieza en
-- 1001); así no se repite aunque compren desde varios navegadores a la vez.
CREATE SEQUENCE seq_numero_pedido START 1001;

-- Estados = ORDER_STATUS de orders.js (+ 'entregado', que lee Seguimiento.jsx).
CREATE TABLE pedido (
    id_pedido            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido        VARCHAR(20)   NOT NULL UNIQUE
                         DEFAULT ('UC-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('seq_numero_pedido')::text, 5, '0'))
                         CHECK (numero_pedido ~ '^UC-[0-9]{4}-[0-9]{5}$'),   -- p. ej. UC-2026-01001
    id_cliente           INT           NOT NULL REFERENCES cliente(id_cliente) ON DELETE RESTRICT,
    id_carrito           INT           REFERENCES carrito(id_carrito) ON DELETE SET NULL,
    estado               VARCHAR(30)   NOT NULL DEFAULT 'creado'
                         CHECK (estado IN ('creado','pagado_simulado','pendiente_preparacion',
                                           'enviado','entregado','cancelado','con_incidencia')),
    -- Datos de envío (paso 1 del checkout: customer.*)
    envio_nombre         VARCHAR(250)  NOT NULL,       -- "nombre apellidos"
    envio_email          VARCHAR(254)  NOT NULL,
    envio_telefono       VARCHAR(30)   NOT NULL,
    envio_direccion      VARCHAR(200)  NOT NULL,       -- solo calle y número
    envio_ciudad         VARCHAR(80)   NOT NULL,
    envio_provincia      VARCHAR(80)   NOT NULL,
    envio_codigopostal   CHAR(5)       NOT NULL CHECK (envio_codigopostal ~ '^[0-9]{5}$'),
    envio_pais           VARCHAR(60)   NOT NULL DEFAULT 'España',
    -- Importes = computeTotals() de pricing.js (el servidor los recalcula siempre)
    subtotal             NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    descuento            NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
    gastos_envio         NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (gastos_envio >= 0),
    total                NUMERIC(10,2) NOT NULL CHECK (total >= 0),
    tipo_iva             NUMERIC(4,2)  NOT NULL DEFAULT 21.00,
    base_imponible       NUMERIC(10,2) NOT NULL,
    impuesto             NUMERIC(10,2) NOT NULL,       -- ivaIncluded
    fecha_creacion       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_actualizacion  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_descuento  CHECK (descuento <= subtotal),
    -- Descuento: 0 o el 10 % del subtotal (DISCOUNT_RATE), con 0,005 de margen por el redondeo de JS.
    -- Que el cliente tenga derecho a él (rol y mes de alta) lo comprueba el backend / 03_consultas.sql (G3).
    CONSTRAINT chk_descuento_tasa CHECK (descuento = 0 OR abs(descuento - subtotal * 0.10) <= 0.005),
    CONSTRAINT chk_total      CHECK (total = subtotal - descuento + gastos_envio),
    CONSTRAINT chk_desglose   CHECK (base_imponible + impuesto = total),
    -- IVA incluido = total - total/1,21 (tolerancia de 1 céntimo por redondeo JS)
    CONSTRAINT chk_iva        CHECK (abs(impuesto - round(total - total / (1 + tipo_iva / 100), 2)) <= 0.01),
    -- Envío: 6,90 €, gratis si subtotal - descuento >= 300 € (SHIPPING_COST / FREE_SHIPPING_FROM).
    -- Si cambian las constantes de pricing.js, actualizar esta restricción.
    CONSTRAINT chk_envio      CHECK (gastos_envio = CASE WHEN subtotal - descuento >= 300 THEN 0 ELSE 6.90 END)
);
CREATE INDEX idx_pedido_cliente ON pedido(id_cliente);
CREATE UNIQUE INDEX uq_pedido_carrito ON pedido(id_carrito);   -- un carrito solo se convierte en un pedido (NULL permitido)
CREATE INDEX idx_pedido_estado  ON pedido(estado);

-- Líneas = order.lines (productId, variantId, variantType/Value, name, brand, unitPrice, qty)
CREATE TABLE linea_pedido (
    id_lineapedido   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido        INT           NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    id_producto      INT           NOT NULL REFERENCES producto(id_producto) ON DELETE RESTRICT,
    id_variante      INT           NOT NULL,
    nombre_producto  VARCHAR(150)  NOT NULL,     -- copia histórica (name)
    marca            VARCHAR(80)   NOT NULL,     -- copia histórica (brand)
    variante_tipo    VARCHAR(10)   NOT NULL CHECK (variante_tipo IN ('Acabado','Color')),   -- variantType
    variante_valor   VARCHAR(60)   NOT NULL,     -- variantValue
    precio_unitario  NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),  -- unitPrice en el momento de la compra
    cantidad         INT           NOT NULL CHECK (cantidad > 0),
    subtotal_linea   NUMERIC(10,2) GENERATED ALWAYS AS (precio_unitario * cantidad) STORED,
    FOREIGN KEY (id_variante, id_producto)
        REFERENCES variante_producto(id_variante, id_producto) ON DELETE RESTRICT,
    UNIQUE (id_pedido, id_variante)
);
CREATE INDEX idx_linea_pedido_variante ON linea_pedido(id_variante, id_producto);
CREATE INDEX idx_linea_pedido_producto ON linea_pedido(id_producto);

-- PAGO (payment de orders.js: id, method, result, at) -------------------
CREATE TABLE pago (
    id_pago          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido        INT           NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
    metodo           VARCHAR(20)   NOT NULL DEFAULT 'paypal_simulado' CHECK (metodo IN ('paypal_simulado')),
    importe          NUMERIC(10,2) NOT NULL CHECK (importe >= 0),
    resultado        VARCHAR(12)   NOT NULL CHECK (resultado IN ('approved','declined')),
                                   -- registerPayment: 'approved' -> pagado_simulado; cualquier otro -> con_incidencia
    referencia_pago  VARCHAR(20)   NOT NULL UNIQUE CHECK (referencia_pago ~ '^PAY-[A-Z0-9]+$'),   -- 'PAY-XXXXXX'
    fecha_creacion   TIMESTAMPTZ   NOT NULL DEFAULT now()                                          -- payment.at
);
CREATE INDEX idx_pago_pedido ON pago(id_pedido);
CREATE UNIQUE INDEX uq_pago_aprobado ON pago(id_pedido) WHERE resultado = 'approved';   -- evita el doble cobro de un pedido

-- INCIDENCIA = ticket del formulario de Soporte -------------------------
-- El pedido es opcional, el usuario puede no tener sesión y el nº de pedido
-- se escribe a mano (solo se valida el formato): se guarda tal cual y,
-- si existe, se enlaza en id_pedido.
CREATE TABLE incidencia (
    id_incidencia          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referencia             VARCHAR(20)  NOT NULL UNIQUE CHECK (referencia ~ '^INC-[A-Z0-9]+$'),   -- 'INC-XXXXXX'
    id_pedido              INT          REFERENCES pedido(id_pedido) ON DELETE SET NULL,
    numero_pedido_indicado VARCHAR(20)  CHECK (numero_pedido_indicado ~ '^UC-[0-9]{4}-[0-9]{5}$'),
    nombre_contacto        VARCHAR(120) NOT NULL,
    email_contacto         VARCHAR(254) NOT NULL,
    asunto                 VARCHAR(200) NOT NULL,
    descripcion            TEXT         NOT NULL,      -- message
    estado                 VARCHAR(12)  NOT NULL DEFAULT 'abierta'
                           CHECK (estado IN ('abierta','en_curso','resuelta','cerrada')),  -- el frontend solo crea 'abierta'
    fecha_creacion         TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_incidencia_pedido ON incidencia(id_pedido);

-- EVENTO (events.js: id, type, timestamp, sessionId, user, payload) -----
CREATE TABLE evento (
    id_evento          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente         INT          REFERENCES cliente(id_cliente)   ON DELETE SET NULL,   -- user (email); NULL = anónimo
    id_producto        INT          REFERENCES producto(id_producto) ON DELETE SET NULL,
    id_pedido          INT          REFERENCES pedido(id_pedido)     ON DELETE SET NULL,
    id_sesion_web      VARCHAR(20),                                                        -- sessionId: 'ses_ab12cd34'
    tipo               VARCHAR(40)  NOT NULL
                       CHECK (tipo IN ('product.viewed','cart.item_added','checkout.started',
                                       'order.created','payment.simulated','support.requested',
                                       'order.status_changed')),
    fecha_creacion     TIMESTAMPTZ  NOT NULL DEFAULT now(),                                -- timestamp
    datos_adicionales  JSONB        NOT NULL DEFAULT '{}'::jsonb                           -- payload tal cual lo genera el frontend
);
CREATE INDEX idx_evento_tipo     ON evento(tipo);
CREATE INDEX idx_evento_fecha    ON evento(fecha_creacion);
CREATE INDEX idx_evento_cliente  ON evento(id_cliente);
CREATE INDEX idx_evento_producto ON evento(id_producto);
CREATE INDEX idx_evento_pedido   ON evento(id_pedido);

-- Trigger: mantener fecha_actualizacion en carrito y pedido ------------
CREATE FUNCTION set_fecha_actualizacion() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
    NEW.fecha_actualizacion := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_carrito_actualizacion BEFORE UPDATE ON carrito
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_pedido_actualizacion BEFORE UPDATE ON pedido
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- Vista del catálogo: SKU y opción base + stock total sumando variantes.
-- security_invoker: respeta RLS (sin esto la vista saltaría el bloqueo de anon).
CREATE VIEW v_catalogo WITH (security_invoker = true) AS
SELECT p.id_producto, p.codigo, c.slug AS categoria, p.marca, p.nombre, p.precio,
       p.tipo_variante, vb.valor AS variante_base, vb.sku AS sku_base,
       COALESCE(sum(v.stock) FILTER (WHERE v.activo), 0)::int AS stock_total,
       p.valoracion, p.num_resenas, p.etiqueta, p.destacado, p.activo
FROM producto p
JOIN categoria c          ON c.id_categoria = p.id_categoria
JOIN variante_producto vb ON vb.id_producto = p.id_producto AND vb.es_base
JOIN variante_producto v  ON v.id_producto  = p.id_producto
GROUP BY p.id_producto, p.codigo, c.slug, c.orden, p.marca, p.nombre, p.precio, p.tipo_variante,
         vb.valor, vb.sku, p.valoracion, p.num_resenas, p.etiqueta, p.destacado, p.activo;

-- Seguridad: RLS activado sin políticas -> la API pública (anon) no
-- puede leer ni escribir; solo el backend con la connection string.
ALTER TABLE categoria         ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto          ENABLE ROW LEVEL SECURITY;
ALTER TABLE conexion          ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto_conexion ENABLE ROW LEVEL SECURITY;
ALTER TABLE variante_producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE cliente           ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesion            ENABLE ROW LEVEL SECURITY;
ALTER TABLE carrito           ENABLE ROW LEVEL SECURITY;
ALTER TABLE linea_carrito     ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedido            ENABLE ROW LEVEL SECURITY;
ALTER TABLE linea_pedido      ENABLE ROW LEVEL SECURITY;
ALTER TABLE pago              ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidencia        ENABLE ROW LEVEL SECURITY;
ALTER TABLE evento            ENABLE ROW LEVEL SECURITY;

COMMIT;
